// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: authn.proto

package authn

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/koverto/uuid"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Authn service

type AuthnService interface {
	Create(ctx context.Context, in *Credential, opts ...client.CallOption) (*CredentialResponse, error)
	Validate(ctx context.Context, in *Credential, opts ...client.CallOption) (*CredentialResponse, error)
	Update(ctx context.Context, in *CredentialUpdate, opts ...client.CallOption) (*CredentialResponse, error)
}

type authnService struct {
	c    client.Client
	name string
}

func NewAuthnService(name string, c client.Client) AuthnService {
	return &authnService{
		c:    c,
		name: name,
	}
}

func (c *authnService) Create(ctx context.Context, in *Credential, opts ...client.CallOption) (*CredentialResponse, error) {
	req := c.c.NewRequest(c.name, "Authn.Create", in)
	out := new(CredentialResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnService) Validate(ctx context.Context, in *Credential, opts ...client.CallOption) (*CredentialResponse, error) {
	req := c.c.NewRequest(c.name, "Authn.Validate", in)
	out := new(CredentialResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authnService) Update(ctx context.Context, in *CredentialUpdate, opts ...client.CallOption) (*CredentialResponse, error) {
	req := c.c.NewRequest(c.name, "Authn.Update", in)
	out := new(CredentialResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authn service

type AuthnHandler interface {
	Create(context.Context, *Credential, *CredentialResponse) error
	Validate(context.Context, *Credential, *CredentialResponse) error
	Update(context.Context, *CredentialUpdate, *CredentialResponse) error
}

func RegisterAuthnHandler(s server.Server, hdlr AuthnHandler, opts ...server.HandlerOption) error {
	type authn interface {
		Create(ctx context.Context, in *Credential, out *CredentialResponse) error
		Validate(ctx context.Context, in *Credential, out *CredentialResponse) error
		Update(ctx context.Context, in *CredentialUpdate, out *CredentialResponse) error
	}
	type Authn struct {
		authn
	}
	h := &authnHandler{hdlr}
	return s.Handle(s.NewHandler(&Authn{h}, opts...))
}

type authnHandler struct {
	AuthnHandler
}

func (h *authnHandler) Create(ctx context.Context, in *Credential, out *CredentialResponse) error {
	return h.AuthnHandler.Create(ctx, in, out)
}

func (h *authnHandler) Validate(ctx context.Context, in *Credential, out *CredentialResponse) error {
	return h.AuthnHandler.Validate(ctx, in, out)
}

func (h *authnHandler) Update(ctx context.Context, in *CredentialUpdate, out *CredentialResponse) error {
	return h.AuthnHandler.Update(ctx, in, out)
}
